# deploy to usernode pool
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aad-app-deployment
  namespace: aad-app
  labels:
    app: aad-app
spec:
    replicas: 2
    selector:
      matchLabels:
        app: aad-app
    template:
      metadata:
        labels:
          app: aad-app
      spec:
        # nodeSelector:
        #  nodepool: userpool
        containers:
        - name: aad-app
          # Replace 1.0.0 with the version of your application that you are building
          image: vhacr1.azurecr.io/aad-app:latest
          # set image PullPolicy to Always to ensure that the latest image is pulled on deployment
          imagePullPolicy: Always
          
          resources:
            # 128Mi bytes of memory and 250 millicpu (1/4 cpu core)
            requests:
              memory: "128Mi"
              cpu: "250m"
            # 256Mi bytes of memory and 500 millicpu (1/2 cpu core)
            limits:
                memory: "256Mi"
                cpu: "500m"
          ports:
          - containerPort: 3000
