apiVersion: v1
kind: Service
metadata:
  name: prisma-service
  namespace: aad-app
spec:
  type: ClusterIP
  selector:
    app: prisma
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000